### ISSUE TITLE
fully encapsulate under-pressure

### ISSUE THREAD

**Issue by mcollina** [smartiniOnGitHub/fastify-healthcheck#1]
under-pressure adds an `onRequest` hook, enabling it _for all routes_. I think the scope of this plugin should be to encapsulate that: the hook should only be triggered by the healthcheck route.

**Comment by smartiniOnGitHub** [comment]
ah ok, so I need to check how to do it ... 
@mcollina sorry, do you have some more hint (the best would be some link or other plugin that behaves in a similar way, for me to look) ?
Because it's not so clear to me how to encapsulate under-pressure in the way you suggest ... thanks a lot.

**Comment by mcollina** [comment]
```js
// note that this is not using fastify-plugin
module.exports = function (app, opts, next) {
  app.register(require('under-pressure'))
  app.get('/healthcheck', ...)
  next()
}
```

**Comment by smartiniOnGitHub** [comment]
ah ok I'll try that way ... thanks.
Update: implementation almost done, now I need to add some more tests to ensure in case of problems I can see them in the healthcheck exposed url ... done.
Last, I need only to do some tests in Docker: with all good it works, so now I need to check with an always failing configuration of 'under-pressure' and see results of healthcheck features of Docker.

**Comment by smartiniOnGitHub** [comment]
@mcollina all done !! Thank you very much for the help and the review :-) . Bye
