### ISSUE TITLE
Fix failing test on expected error 503

### ISSUE THREAD

**Issue by smartiniOnGitHub** [smartiniOnGitHub/fastify-healthcheck#12]
After yesterday merge of [PR#11](https://github.com/smartiniOnGitHub/fastify-healthcheck/pull/11) I see a consistent failure in some tests here; note that failures shouldn't be related to those changes but to other: maybe my way to use some flag from under-pressure, or something related to my way to instantiate the Fastify server in tests.
This issue is to track the activity on it, and (hopefully) a quick fix.
Note that my plugin examples (positive and even the always failing) works as expected, so it seems something related to only my tests here.

**Comment by smartiniOnGitHub** [comment]
@afonsojramos FYI I'm looking at it ...
Small update: even a similar test (put inside my test source) that uses directly under-pressure fails again (like mine), but the same test in under-pressure repo works; I need to check something even in my tests execution (flags ? other ?) ...

**Comment by afonsojramos** [comment]
@smartiniOnGitHub Maybe a focus first on reducing the dependencies might be a good call in that case. You never know what might be causing the issue 🤷‍♂️

**Comment by smartiniOnGitHub** [comment]
Removed 'standardx' dev dependency and aligned linting and TypeScript checks with the ones in [Fastify](https://github.com/fastify/fastify), see related issue #14 (just closed).

Then, added a test to test 503 errors (like mine currently failing) directly from [under-pressure](https://github.com/fastify/under-pressure) plugin but it fails even here, I need to investigate further ...

**Comment by smartiniOnGitHub** [comment]
Fixed failing tests in commit: [4cb0b7e9e284a6166e5603986458fba2dd062538](https://github.com/smartiniOnGitHub/fastify-healthcheck/commit/4cb0b7e9e284a6166e5603986458fba2dd062538) and consistent (it always work).

For better consistency with under-pressure, I just reverted the requirement to Fastify '^3.0.0'.

**Comment by smartiniOnGitHub** [comment]
@afonsojramos I'll try to implement even another feature, see [issue#15](https://github.com/smartiniOnGitHub/fastify-healthcheck/issues/15); or if too complex, in a few days I'll publish a new plugin version with current feature (and postpone that feature to next release); hope it's good. Bye

**Comment by afonsojramos** [comment]
Looking good! Thanks! :)
