### ISSUE TITLE
Handle under-pressure custom response from healthCheck function

### ISSUE THREAD

**Issue by smartiniOnGitHub** [smartiniOnGitHub/fastify-healthcheck#15]
Since v5.5.0, under-pressure, see its release notes [here](https://github.com/fastify/under-pressure/releases/tag/v5.5.0).
Add the ability to use that feature directly from (this) plugin options, if possible.

**Comment by afonsojramos** [comment]
Any news on this? If you want I can try and help

**Comment by smartiniOnGitHub** [comment]
Hi, yes I'm working on it,  and just fixed a small bug seen by integrating a test on this feature.
Hope to complete this today or max tomorrow, so I can publish the new plugin release ... sorry for the delay.
Stay well. Bye

**Comment by smartiniOnGitHub** [comment]
Added a test to ensure the plugin is compatible in today commit [c86c6549027a0374fd4a0f63c9425f5b536ed979](https://github.com/smartiniOnGitHub/fastify-healthcheck/commit/c86c6549027a0374fd4a0f63c9425f5b536ed979); now I'm ready to publish the release.
