### ISSUE TITLE
Support Fastify 4

### ISSUE THREAD

**Issue by bcomnes** [smartiniOnGitHub/fastify-healthcheck#16]
Any plans on supporting Fastify 4? Want any help?

**Comment by smartiniOnGitHub** [comment]
Hi, yes I'll do during next days, got not time before, sorry ... 
Stay tuned :) . Bye

**Comment by bcomnes** [comment]
Sounds good no problem

**Comment by smartiniOnGitHub** [comment]
Plugin release 4.0.0 for Fastify 4.x (and so Node.js 14 LTS) using latest release of the (scoped) package '@fastify/under-pressure' 7.x has just been published; hope it's good. Bye

**Comment by bcomnes** [comment]
Woo! Thank you ✌️
