### ISSUE TITLE
New version incompatible with Node versions < 18

### ISSUE THREAD

**Issue by kibertoad** [smartiniOnGitHub/fastify-healthcheck#19]
See https://fusebit.io/blog/node-18-prefix-only-modules/?utm_source=www.google.com&utm_medium=referral&utm_campaign=none
Node core prefixes are not available in older Node versions.

**Comment by kibertoad** [comment]
See https://github.com/smartiniOnGitHub/fastify-healthcheck/pull/18#issuecomment-1234777762

**Comment by smartiniOnGitHub** [comment]
Just for completeness, I put here the same comment of the other PR (if useful to someone reading this issue):
```
For example I just found:
https://www.wisdomgeek.com/development/web-development/javascript/node-js-introduces-node-protocol-imports/
as they write, it seems that this new prefix is available since:

v16.0.0, v14.18.0 (ESM import and CommonJS require())

anyway, I just re-verified all with Node.js v14.20.0 and 16.17.0 and I confirm all works the same.
```
