### ISSUE TITLE
Fastify v2 support?

### ISSUE THREAD

**Issue by bkw** [smartiniOnGitHub/fastify-healthcheck#2]
Hi,

I was wondering: now that under-pressure released an @next version (See fastify/under-pressure#21), are there any plans to do the same with fastify-healthcheck?

**Comment by smartiniOnGitHub** [comment]
Hi, sure even if not really planned :-) ... for sure I need to update this (and all my other plugins) to Fastify v2 (starting from fastify-cloudevents to support all new hooks), I can do some initial work next week on a feature branch and keep you updated.
If you have some case that I could test or have some time to help me, I'll be happy.
Thanks for now, Sandro

**Comment by smartiniOnGitHub** [comment]
Hi, I have some updates (soon a maintenance release) using 'under-pressure' 1.x; after I'll do changes (in a branch, to merge later) for using 'under-pressure' 2.x , sorry for the deplay ...

**Comment by smartiniOnGitHub** [comment]
@bkw Hi, in a branch 'compatibility-with-fastify_v2' I just updated dependencies for Fastify v2 (at the moment '2.0.0-rc.5') and all seems to work; are you able to test from sources (that branch) or do you need a plugin release to do some tests (published as next, like '2.0.0-rc.1') ?

**Comment by bkw** [comment]
Thanks for reaching out, I’m afraid I wont be of much help, though. I switched to using just under-pressure, which turned out to be good enough for my use case. Moreover, I’m no longer working for the project that I used this for. My new gig does not use fastify (not yet, I presume). 

Thanks and best wishes!
