### ISSUE TITLE
NodeNext compatibility

### ISSUE THREAD

**Issue by marcoreni** [smartiniOnGitHub/fastify-healthcheck#20]
When using this plugin with `moduleResolution: nodeNext`, we encounter the same error as https://github.com/fastify/fastify-cors/issues/223 .

**Comment by smartiniOnGitHub** [comment]
Hi, thanks for the issue, but could you give me a minimal example to reproduce the error or is it the same of the linked issue ?
With the workaround seen [there](https://github.com/fastify/fastify-cors/issues/223#issuecomment-1286662511), does it work ?
I see there is a related bug opened in Fastify, see [here](https://github.com/fastify/fastify/issues/4435); let's check after it has been resolved and see if something can be fixed/improved even in this plugin.
Thanks a lot.

**Comment by marcoreni** [comment]
Hei @smartiniOnGitHub , I opened that bug in Fastify but it's not related to this.

The workaround works, however it's just a double typecast and it does not solve the issue per se.

Repro here: https://www.typescriptlang.org/play?target=99&moduleResolution=99&module=199#code/JYWwDg9gTgLgBAbzgMwIYGcbGQTwDRwBiGWuACgDYCuA5sAHYDCqFFARqgMYDWcAviigQQcAERpM2HKIDcAWABQoSLERwwDCP0HCxG+hFmLl0eBNI4AEgFMWMABad71ngSTFJuG3cfOeAeTAsCHp0bWQhEXESKQBaZx8nF24jBUVOEMw4dGsoADdcuABeFBjcAAokCggaGlyALnVNcoBKfjaAeg64AB5Y2LgDOAz6ZGAaKihUYPpFdMz4ISoYazCSjBx6TjhyhkxULetGmBwwawhkbNyCqBbGskjgHJ68iGAAEwA+Yu+ERTg4HsYAdONYAHR1GDlUQdDhQURuPgEDZbHZQVYEdFgCg4NpFX7-AFwdEwSb0YnWbE4ME5ejvaEQFIteQKAF8ZmKPhzBSoADuqGA8By+VyYPRdEwuXK5ik3goDiSPGZcC6cAAIhBVoMIPBedBuNy+QKhddReKnisoNKylZbPLfMk4Bg4FR6NwDLzyc6PBZKLQGMxWBweD0fbK7Qq-NxAjN0J9laqAJK6-XoAhsZaAmAAcjCBxdNBxcD1UG4qCWdKAA

NOTE: for some reason the link above does not retain "NodeNext": you need to go into TSConfig and specify it:

<img width="359" alt="image" src="https://user-images.githubusercontent.com/2797489/203515053-45e32e40-9f49-486d-82c1-68b453de1943.png">

**Comment by smartiniOnGitHub** [comment]
ok perfect I'll take a look during next days and tell you something ...
Thanks for now. Bye

**Comment by smartiniOnGitHub** [comment]
Hi, now I better understand the problem; but I have a little TypeScript knowledge so I'll need some time for the fix.
Anyway suggestions/PR are welcome in the meantime. Thanks for now. Bye

**Comment by smartiniOnGitHub** [comment]
Sorry this is longer than expected ... anyway in the repo you can see that I started the work on it (bump next release that will be 4.3.0 and upgrading all dependencies to latest, to be sure that all will be good); I'll tell more soon. Bye

**Comment by smartiniOnGitHub** [comment]
Update: changes almost done and all seems to work; now I only have to let the linter handle the new code in the right way.
Soon I'll raise a PR so if needed you can take a look and maybe do some tests before the merge.

**Comment by smartiniOnGitHub** [comment]
@marcoreni Hi, PR with code changes opened, please take a look at changes; I tested in another sample project that uses TypeScript with NodeNext and all should be fine. If not tell me, otherwise in a few days I'll merge this and prepare for a next plugin release. Thanks. Bye

**Comment by marcoreni** [comment]
Hei @smartiniOnGitHub , I did a quick&dirty check by replacing the `.d.ts` file in the package with the one from the PR and it seems to work.

**Comment by smartiniOnGitHub** [comment]
Release 4.3.0 of the plugin with the fix just published. Bye
