### ISSUE TITLE
Feature request: option to customize http method

### ISSUE THREAD

**Issue by nocive** [smartiniOnGitHub/fastify-healthcheck#23]
Hello :wave: 

Would you consider exposing a new option to be able to customize the http method?
We would love to be able to use HEAD requests with this plugin instead of normal GET :)

**Comment by smartiniOnGitHub** [comment]
Hi, sure if useful we can add ... could you send a PR so I can take a look ?
Thanks for the idea and the help :-) .

**Comment by smartiniOnGitHub** [comment]
Hi @nocive did you try with HEAD request, if it's already exposed ? Didn't tried (yet) here.
From what I see [here](https://github.com/fastify/fastify/pull/2700) it should be something already available, unless explicitly disabled. 
Tell me. Bye

**Comment by smartiniOnGitHub** [comment]
Hi, running the example application provided with plugin sources I confirm that Fastify default behavior is by default to expose even a HEAD route for each route exposed, so for example:
```
> node example/example

Available Routes:
└── / (GET)
    / (HEAD)
    └── health (GET)
        health (HEAD)

Server listening on http://0.0.0.0:3000
```
from another terminal, if you send some queries you can see that all is already returned (but only headers, no data):
```
$ curl --head http://localhost:3000/health
HTTP/1.1 200 OK
content-type: text/html; charset=utf-8
Date: Thu, 23 Feb 2023 18:47:43 GMT
Connection: keep-alive
Keep-Alive: timeout=72
```
or 
```
curl -X HEAD http://localhost:3000/health
```
but no content will be shown in this case.

Reference: [HEAD - HTTP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD).

**Comment by smartiniOnGitHub** [comment]
Unless objections in a few days I'll close this issue, tell me otherwise. Bye

**Comment by nocive** [comment]
I guess it's not supported by the fastify core versions we're currently using, we're lagging a few versions behind and it's not working for us.
Thanks for looking into it though, appreciate it :+1:

**Comment by smartiniOnGitHub** [comment]
Uh sorry for that ...
