### ISSUE TITLE
TypeScript types

### ISSUE THREAD

**Issue by kibertoad** [smartiniOnGitHub/fastify-healthcheck#4]
Would you accept a PR with TypeScript typings?

**Comment by smartiniOnGitHub** [comment]
Hi, yes sure, thanks a lot.
Then how can I test them ? Would you provide some test or an example ? Otherwise would you help me setup something here ?

**Comment by kibertoad** [comment]
Yes, of course.

**Comment by smartiniOnGitHub** [comment]
@kibertoad note that I just update the code to add a new plugin option, another boolean flag ...

**Comment by kibertoad** [comment]
Gotcha. Will submit a PR today.

**Comment by smartiniOnGitHub** [comment]
Thank you very much, for this welcome addition !!
