### ISSUE TITLE
Typescript types are wrong

### ISSUE THREAD

**Issue by m-ronchi** [smartiniOnGitHub/fastify-healthcheck#7]
this plugin declared type is not compatible with fastify.register(...), leading to a compile error

repro:
1) create a .ts file with
```ts
import fastify from "fastify";
import fastifyHealth from "fastify-healthcheck";

fastify().register(fastifyHealth);
```
2) try to compile it

expected: compile succeeds
actual: compile fails with 
```
Argument of type 'FastifyMiddleware<Server, IncomingMessage, ServerResponse, DefaultQuery, DefaultParams, DefaultHeaders, any>' is not assignable to parameter of type '(instance: FastifyInstance<Server, IncomingMessage, ServerResponse>, options: FastifyReply<ServerResponse>, callback: (err?: FastifyError | undefined) => void) => void'.
  Types of parameters 'req' and 'instance' are incompatible.
    Type 'FastifyInstance<Server, IncomingMessage, ServerResponse>' is missing the following properties from type 'FastifyRequest<IncomingMessage, DefaultQuery, DefaultParams, DefaultHeaders, any>': query, params, headers, body, and 8 more.ts(2345)
```

**Comment by smartiniOnGitHub** [comment]
Hi @m-ronchi , I'll take a look ASAP, and keep you updated. Thanks for now.

**Comment by smartiniOnGitHub** [comment]
@m-ronchi  these types definitions only works for Fastify v2.0, and current plugin release is only for that version (it's in plugin requirements and constraints); next major release of the plugin will be compatible with Fastify v3.
In plugin types folder there is a minimal TypeScript example that uses types defined here, hope it's good. Bye

@kibertoad sorry, maybe you have some more info for the guy ...

**Comment by kibertoad** [comment]
Yes, that is correct. Unfortunately, there is no way to support both. @smartiniOnGitHub let me know if you'd like me to submit a pr that will change types into v3 version.

**Comment by m-ronchi** [comment]
I am using fastify version 2.14.1, not v3

[bug.zip](https://github.com/smartiniOnGitHub/fastify-healthcheck/files/4710186/bug.zip)

**Comment by kibertoad** [comment]
I'll check this right now.

**Comment by kibertoad** [comment]
Thank you for reporting this. There does seem to be an issue, and I'm trying to understand why neither test nor compiler is complaining...

**Comment by smartiniOnGitHub** [comment]
All should be fine now; thanks to all for identifying the problem and fixing it, I'll do some test and if possible today I'll publish a patch release for the plugin.

**Comment by smartiniOnGitHub** [comment]
Plugin release 2.3.1 just published, thank you again.
If other problems should arise, tell me. Bye
